[package]
name = "cycles"
version = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time_series = { path = "../../time_series" }
simplelog = "0.12.0"
log = "0.4"
time = "0.3.14"
