[package]
name = "fractals"
version = "0.1.0"
edition = "2021"

[dependencies]
# internal deps
time_series = { path = "../../time_series" }
# external deps
tokio = { version = "1.24.1", features = ["full"] }
log = "0.4"
simplelog = "0.12.0"
plotters = "0.3.4"
chrono = "0.4.22"