[package]
name = "date"
version = "0.2.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time_series = { path = "../../time_series" }
simplelog = "0.12.0"
log = "0.4"
time = "0.3.14"