[package]
name = "alpaca_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time_series = { path = "../../time_series" }
alpaca-finance = "0.2.1"
