name: Build binary
description: Builds the Lunar Engine binary

runs:
  using: "composite"
  steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Installing system requirements
      run: |
        sudo apt-get update
        sudo apt-get install -y libudev-dev libssl-dev libsasl2-dev libzstd-dev
      shell: bash

    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release

    - name: Upload Lunar Engine Artifact
      uses: actions/upload-artifact@v3
      with:
        name: lunar-engine
        retention-days: 5
        path: target/release/server_app